name: tests

on:
  pull_request:
  push:
    branches:
      - main
  release:

env:
  default-python: "3.12"
  minimum-supported-python: "3.11"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: make init

      - name: Run lint
        run: make lint

      - name: Run typecheck
        run: make typecheck

      - name: Run tests
        run: make test

  run-coveralls:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: make init

      - name: Generate coverage
        run: |
          make test
          coverage lcov

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
