name: tests

on:
  push:

env:
  default-python: "3.13"
  minimum-supported-python: "3.9"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Activate virtual environment
        run: |
          uv venv
          source .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Install dependencies
        run: make init

      - name: Run lint
        run: make lint

      - name: Run typecheck
        run: make typecheck

      - name: Run tests
        run: make test

  upload-coverage:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Activate virtual environment
        run: |
          uv venv
          source .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Install dependencies
        run: make init

      - name: Run tests
        run: pytest --cov=l2m2 --cov=test_utils --cov-report=lcov

      - name: Upload coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
